name: Build Base

on:
 push:

env:
  DOCKER_VERSION: 26

jobs:
  Macos:
    strategy:
      fail-fast: false
      matrix:
        target:
          - native_dyn
          - iOS_arm64
          - iOS_i386
          - iOS_x86_64
          - iOS_armv7
    runs-on: macos-latest
    env:
      SSH_KEY: /tmp/id_rsa
      OS_NAME: osx
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install packages
      uses: mstksg/get-package@v1
      with:
        brew: pkg-config ninja
    - name: Install python modules
      run: |
        pip3 install meson==0.50.0 pytest
        pip3 install --no-deps $GITHUB_WORKSPACE
    - name: secret
      shell: bash
      run: |
        echo "${{secrets.ssh_key}}" > $SSH_KEY
        chmod 600 $SSH_KEY
    - name: Dump file
      shell: bash
      run: cat /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/machine/_types.h
    - name: Ensure base deps
      shell: bash
      run: |
        cd $HOME
        $GITHUB_WORKSPACE/.github/scripts/ensure_base_deps.py
      env:
        PLATFORM_TARGET: ${{matrix.target}}
    - name: Compile all deps
      shell: bash
      run: |
        cd $HOME
        $GITHUB_WORKSPACE/.github/scripts/compile_all_deps.py
      env:
        PLATFORM_TARGET: ${{matrix.target}}
    - name: Upload failure logs
      if: failure()
      run: $GITHUB_WORKSPACE/.github/scripts/upload_failure_logs.sh
      env:
        PLATFORM_TARGET: ${{matrix.target}}
