name: CD

on:
 push:

jobs:
  Flatpak-temp:
    strategy:
      fail-fast: false
    env:
      HOME: /home/runner
      SSH_KEY: /tmp/id_rsa
      COMPILE_CONFIG: flatpak
      OS_NAME: focal
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      shell: bash
      run: |
        cd $HOME
        git clone https://github.com/${REP}
        cd ./${REP##*/}
        git checkout --force ${GITHUB_SHA}
        pip3 install --user --no-deps .
      env:
        REP: ${{github.repository}}
    - name: Install flatpak tools
      run: |
        sudo apt-get update
        sudo apt-get install flatpak-builder ninja-build meson
    - name: secret
      shell: bash
      run: |
        echo "${{secrets.ssh_key}}" > $SSH_KEY
        chmod 600 $SSH_KEY
    - name: Ensure base deps
      shell: bash
      run: |
        cd $HOME
        kiwix-build/.github/scripts/ensure_base_deps.py
    - name: Build release
      shell: bash
      run: |
        cd $HOME
        kiwix-build/.github/scripts/build_release_nightly.py
    - name: Upload failure logs
      if: failure()
      run: $HOME/kiwix-build/.github/scripts/upload_failure_logs.py
