name: Test libcurl iOS

on:
 push:

jobs:
  Macos:
    runs-on: macos-latest
    env:
      OS_NAME: osx
      CFLAGS: -arch arm64 -pipe -Os -isysroot /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=9.0 -fembed-bitcode
      LDFLAGS: -arch arm64 -isysroot /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
    steps:
    - name: Checkout code
      shell: bash
      run: |
        curl https://curl.haxx.se/download/curl-7.68.0.tar.gz -o curl.tar.gz
        mkdir SOURCE
        tar -xzf curl.tar.gz -C SOURCE --strip-components 1
    - name: Configure
      shell: bash
      run: |
        mkdir BUILD
        cd BUILD
        ../SOURCE/configure --host="arm-apple-darwin" \
          --disable-shared \
          --enable-static \
          --disable-smtp \
          --disable-pop3 \
          --disable-imap \
          --disable-ftp \
          --disable-tftp \
          --disable-telnet \
          --disable-rtsp \
          --disable-ldap \
          --disable-file \
          --disable-ldaps \
          --disable-dict \
          --disable-smb \
          --disable-gopher \
          --disable-manual \
          --with-darwinssl
    - name: Build
      shell: bash
      run: |
        cd BUILD
        make
